RTXINFO:
  CONFIG_SERVER: "araxconfig@araxconfig.rtx.ai"
  GITHUB_LINK: " https://raw.githubusercontent.com/RTXteam/RTX/kg2.10.0c"
  SECRET_CONFIGFILE: "config_secrets.json"
  DB_CONFIGFILE: "config_dbs.json"

DRUGMECHDBINFO:
  LINK: "https://raw.githubusercontent.com/SuLab/DrugMechDB/main"
  DRUGMECHDB_PATH: "indication_paths.yaml"

KG2INFO:
  BIOLINK_VERSION: "4.2.0"
  PUBLICATION_CUTOFF: 10
  NGD_CUTOFF: 0.6

SYSTEMINFO:
  NUM_CPU: 200

TRAINING_DATA:
  TP:
    MYCHEM: raw_training_data/mychem_tp.txt
    SEMMED: raw_training_data/semmed_tp.txt
    NDF: raw_training_data/ndf_tp.txt
    REPODB: raw_training_data/repoDB_tp.txt
  TN:
    MYCHEM: raw_training_data/mychem_tn.txt
    SEMMED: raw_training_data/semmed_tn.txt
    NDF: raw_training_data/ndf_tn.txt
    REPODB: raw_training_data/repoDB_tn.txt
  DRUGBANK_XML: drugbank.xml
  MOLEPRO_API_LINK: https://molepro-trapi.transltr.io/molepro/trapi/v1.5

MODELINFO:
  PARAMS:
    BANDWIDTH: 3000
    MAX_PATH: 3
    BUCKET_INTERVAL: 50
    SEED: 1023
    GPU: 1
    STATE_HISTORY: 2
    LEARNING_RATE: 0.0005
    
PARALLEL_PRECOMPUTE:
  K: 25
  N_drugs: 150
  N_paths: 50
  BATCH_SIZE: 200

DATABASE:
  DATABASE_NAME: 'ExplainableDTD.db'
