DRUGMECHDBINFO:
  LINK: "https://raw.githubusercontent.com/SuLab/DrugMechDB/main"
  DRUGMECHDB_PATH: "indication_paths.yaml"

TRANSLATOR_KG:
  DOWNLOAD_URL: "https://kgx-storage.rtx.ai/releases/translator_kg/latest/translator_kg.tar.zst"
  NODES_JSONL: "translator_kg/nodes.jsonl"
  EDGES_JSONL: "translator_kg/edges.jsonl"

GROUND_TRUTH_PAIRS:
  DIR: "ground_truth_pairs"
  BASE_URL: "https://github.com/everycure-org/matrix-indication-list/releases/download/v1.4.1"
  INDICATION_FILE: "indicationList.xlsx"
  CONTRAINDICATION_FILE: "contraindicationList.xlsx"

DRUG_DISEASE_LIST:
  DIR: "drug_disease_list"
  DRUG_DATASET: "everycure/drug-list"
  DRUG_FILE: "matrix-drug-list.tsv"
  DISEASE_DATASET: "everycure/disease-list"
  DISEASE_FILE: "matrix-disease-list.tsv"

KGINFO:
  BIOLINK_VERSION: "4.3.6"
  PUBLICATION_CUTOFF: 10

EXTERNAL_DATA:
  DRUGBANK_XML: drugbank.xml

MODELINFO:
  PARAMS:
    BANDWIDTH: 3000
    MAX_PATH: 3
    BUCKET_INTERVAL: 50
    SEED: 1023
    GPU: 1
    STATE_HISTORY: 2
    LEARNING_RATE: 0.0005
    EXPERT_PATH_PROCESS: 180
    EXPERT_PATH_BATCH_SIZE: 500
    OPTUNA_N_TRIALS: 25
    OPTUNA_N_STARTUP_TRIALS: 5
    EARLY_STOPPING_ROUNDS: 30
    
PARALLEL_PRECOMPUTE:
  K: 100
  N_drugs: 150
  N_paths: 50
  BATCH_SIZE: 200

DATABASE:
  DATABASE_NAME: 'ExplainableDTD_tier0-20260408.db'
